version: '3'

services:
  notebook:
    build: ./jupyter
    user: root
    volumes:
      - "./data:/home/jovyan/work"
    ports:
      - "8888:8888"
    environment:
      NB_UID: 500
      GRANT_SUDO: "yes"
    restart: unless-stopped
    command: start.sh jupyter lab
